version: 2.1.1.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: toofz.NecroDancer.Leaderboards.ReplaysService
  PROJECT_PACKAGE: toofz-replays-service-v%APPVEYOR_BUILD_VERSION%.msi
  COVERALLS_REPO_TOKEN:
    secure: L38QT8owBrci3+aHCjNUkOdToxGlK2aL+ApnPlvwyQyYHFFvBE3CqAiRrmc9j3mP
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_SERVICE_JOB_ID: '%APPVEYOR_JOB_ID%'
artifacts:
  - path: Installer\bin\$(configuration)\$(PROJECT_PACKAGE)
    name: ReplaysService
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=

install:
  - ps: .\Install-AzureStorageEmulator.ps1

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: $(PROJECT).sln
  verbosity: minimal

test_script:
  - ps: .\Test-Project.ps1 -Assembly ReplaysService
after_test:
  - ps: .\Submit-CodeCoverageResults.ps1

deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true
