coverage:
  notify:
    slack:
      default:
        url: secret:MtvC0YwbW225w1IfbGtCYGbC0jjMKF1fNk1Gu5x2oMnsDS+gYkzfkZsjHzB3GZB2jROwIOmPu28qzT8ecKVsm/83yxYpvfN+EXzUvnD78ukIrDmODPbHSkRiCooOp73oYpkgx91YyDzLcuqInxA/MeCAw7Jba7giVT6ODrct5+o=
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null