//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.NecroDancer.Leaderboards.ReplaysService.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FullCycleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FullCycleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.NecroDancer.Leaderboards.ReplaysService.Tests.Properties.FullCycleResources" +
                            "", typeof(FullCycleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _12_9_2017_PROD_SCORE173_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("_12_9_2017_PROD_SCORE173_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _12_9_2017_PROD_SCORE20_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("_12_9_2017_PROD_SCORE20_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _12_9_2017_PROD_SCORE25_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("_12_9_2017_PROD_SCORE25_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _12_9_2017_PROD_SCORE31_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("_12_9_2017_PROD_SCORE31_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _12_9_2017_PROD_SCORE51_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("_12_9_2017_PROD_SCORE51_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _6_9_2017_PROD_SCORE112_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("_6_9_2017_PROD_SCORE112_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _6_9_2017_PROD_SCORE186_ZONE1_LEVEL4 {
            get {
                object obj = ResourceManager.GetObject("_6_9_2017_PROD_SCORE186_ZONE1_LEVEL4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _6_9_2017_PROD_SCORE210_ZONE1_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("_6_9_2017_PROD_SCORE210_ZONE1_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _6_9_2017_PROD_SCORE2916_ZONE4_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("_6_9_2017_PROD_SCORE2916_ZONE4_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _6_9_2017_PROD_SCORE59_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("_6_9_2017_PROD_SCORE59_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _6_9_2017_PROD_SCORE705_ZONE2_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("_6_9_2017_PROD_SCORE705_ZONE2_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_12_9_2017_PROD_SCORE210_ZONE1_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("DLC_12_9_2017_PROD_SCORE210_ZONE1_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_12_9_2017_PROD_SCORE83_ZONE1_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("DLC_12_9_2017_PROD_SCORE83_ZONE1_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_5_9_2017_PROD_SCORE1195_ZONE3_LEVEL4 {
            get {
                object obj = ResourceManager.GetObject("DLC_5_9_2017_PROD_SCORE1195_ZONE3_LEVEL4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_5_9_2017_PROD_SCORE174_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("DLC_5_9_2017_PROD_SCORE174_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_6_9_2017_PROD_SCORE1305_ZONE2_LEVEL4 {
            get {
                object obj = ResourceManager.GetObject("DLC_6_9_2017_PROD_SCORE1305_ZONE2_LEVEL4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_6_9_2017_PROD_SCORE3892_ZONE5_LEVEL6 {
            get {
                object obj = ResourceManager.GetObject("DLC_6_9_2017_PROD_SCORE3892_ZONE5_LEVEL6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_6_9_2017_PROD_SCORE4410_ZONE3_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("DLC_6_9_2017_PROD_SCORE4410_ZONE3_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_6_9_2017_PROD_SCORE5982_ZONE3_LEVEL4 {
            get {
                object obj = ResourceManager.GetObject("DLC_6_9_2017_PROD_SCORE5982_ZONE3_LEVEL4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_6_9_2017_PROD_SCORE7759_ZONE5_LEVEL5 {
            get {
                object obj = ResourceManager.GetObject("DLC_6_9_2017_PROD_SCORE7759_ZONE5_LEVEL5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_Aria_PROD_SCORE375_ZONE1_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_Aria_PROD_SCORE375_ZONE1_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_Bard_PHASING_PROD_SCORE4484_ZONE5_LEVEL6 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_Bard_PHASING_PROD_SCORE4484_ZONE5_LEVEL6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_Diamond_RANDOMIZER_PROD_SCORE246_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_Diamond_RANDOMIZER_PROD_SCORE246_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_Melody_MYSTERY_PROD_SCORE3398_ZONE5_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_Melody_MYSTERY_PROD_SCORE3398_ZONE5_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_Melody_PROD_SCORE317_ZONE1_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_Melody_PROD_SCORE317_ZONE1_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_MYSTERY_PROD_SCORE188_ZONE1_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_MYSTERY_PROD_SCORE188_ZONE1_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_MYSTERY_PROD_SCORE278_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_MYSTERY_PROD_SCORE278_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_MYSTERY_PROD_SCORE487_ZONE1_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_MYSTERY_PROD_SCORE487_ZONE1_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_MYSTERY_PROD_SCORE87_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_MYSTERY_PROD_SCORE87_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_Nocturna_PROD_SCORE488_ZONE2_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_Nocturna_PROD_SCORE488_ZONE2_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_PHASING_PROD_SCORE209_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_PHASING_PROD_SCORE209_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_PROD_SCORE191_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_PROD_SCORE191_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_PROD_SCORE312_ZONE1_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_PROD_SCORE312_ZONE1_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_PROD_SCORE396_ZONE2_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_PROD_SCORE396_ZONE2_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_RANDOMIZER_PROD_SCORE171_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_RANDOMIZER_PROD_SCORE171_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_RANDOMIZER_PROD_SCORE2119_ZONE3_LEVEL4 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_RANDOMIZER_PROD_SCORE2119_ZONE3_LEVEL4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_RANDOMIZER_PROD_SCORE4034_ZONE4_LEVEL4 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_RANDOMIZER_PROD_SCORE4034_ZONE4_LEVEL4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_SEEDED_HARD_PROD_SCORE2668_ZONE5_LEVEL6 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_SEEDED_HARD_PROD_SCORE2668_ZONE5_LEVEL6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_HARDCORE_Tempo_HARD_PROD_SCORE1320_ZONE1_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("DLC_HARDCORE_Tempo_HARD_PROD_SCORE1320_ZONE1_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_SEEDED_SPEEDRUN_HARD_PROD_SCORE97659881_ZONE5_LEVEL6 {
            get {
                object obj = ResourceManager.GetObject("DLC_SEEDED_SPEEDRUN_HARD_PROD_SCORE97659881_ZONE5_LEVEL6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_SPEEDRUN_Bard_PHASING_PROD_SCORE98017110_ZONE5_LEVEL6 {
            get {
                object obj = ResourceManager.GetObject("DLC_SPEEDRUN_Bard_PHASING_PROD_SCORE98017110_ZONE5_LEVEL6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_SPEEDRUN_PROD_SCORE97460146_ZONE5_LEVEL6 {
            get {
                object obj = ResourceManager.GetObject("DLC_SPEEDRUN_PROD_SCORE97460146_ZONE5_LEVEL6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_SPEEDRUN_PROD_SCORE97674899_ZONE5_LEVEL6 {
            get {
                object obj = ResourceManager.GetObject("DLC_SPEEDRUN_PROD_SCORE97674899_ZONE5_LEVEL6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_Aria_PROD_SCORE265_ZONE4_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_Aria_PROD_SCORE265_ZONE4_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_Bard_PROD_SCORE102_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_Bard_PROD_SCORE102_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_Monk_DEATHLESS_PROD_SCORE0_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_Monk_DEATHLESS_PROD_SCORE0_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_Monk_PROD_SCORE6_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_Monk_PROD_SCORE6_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_PROD_SCORE272_ZONE2_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_PROD_SCORE272_ZONE2_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_PROD_SCORE52_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_PROD_SCORE52_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_PROD_SCORE534_ZONE1_LEVEL4 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_PROD_SCORE534_ZONE1_LEVEL4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_PROD_SCORE643_ZONE4_LEVEL6 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_PROD_SCORE643_ZONE4_LEVEL6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_SEEDED_PROD_SCORE0_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_SEEDED_PROD_SCORE0_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_SEEDED_PROD_SCORE55_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_SEEDED_PROD_SCORE55_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_Story_Mode_PROD_SCORE121_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_Story_Mode_PROD_SCORE121_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_Story_Mode_PROD_SCORE143_ZONE1_LEVEL3 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_Story_Mode_PROD_SCORE143_ZONE1_LEVEL3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_Story_Mode_PROD_SCORE165_ZONE1_LEVEL2 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_Story_Mode_PROD_SCORE165_ZONE1_LEVEL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARDCORE_Story_Mode_PROD_SCORE27_ZONE1_LEVEL1 {
            get {
                object obj = ResourceManager.GetObject("HARDCORE_Story_Mode_PROD_SCORE27_ZONE1_LEVEL1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;An error has occurred.&quot;}.
        /// </summary>
        internal static string PostReplaysError {
            get {
                return ResourceManager.GetString("PostReplaysError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SPEEDRUN_Bard_PROD_SCORE98525016_ZONE4_LEVEL6 {
            get {
                object obj = ResourceManager.GetObject("SPEEDRUN_Bard_PROD_SCORE98525016_ZONE4_LEVEL6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SPEEDRUN_PROD_SCORE98067457_ZONE4_LEVEL6 {
            get {
                object obj = ResourceManager.GetObject("SPEEDRUN_PROD_SCORE98067457_ZONE4_LEVEL6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 69408,
        ///  &quot;replays&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;844845073340377377&quot;,
        ///      &quot;error&quot;: null,
        ///      &quot;seed&quot;: null,
        ///      &quot;version&quot;: null,
        ///      &quot;killed_by&quot;: null
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;845970274592369232&quot;,
        ///      &quot;error&quot;: null,
        ///      &quot;seed&quot;: null,
        ///      &quot;version&quot;: null,
        ///      &quot;killed_by&quot;: null
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string StaleReplays {
            get {
                return ResourceManager.GetString("StaleReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE_PROD_SCORE52_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340377377/ECD1D490139C0EE48C876964B16AF3E1EEEA854E/&quot;,
        ///		&quot;size&quot;: 1935
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340377377 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340377377", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;12/9/2017_PROD_SCORE51_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340436306/3CEADC5265EA982F1817C7D69223350AA002D3E8/&quot;,
        ///		&quot;size&quot;: 568
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340436306 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340436306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE Story Mode_PROD_SCORE121_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340472702/9C96265F0CA963484156A6EE2ACB0F16899A9E23/&quot;,
        ///		&quot;size&quot;: 2003
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340472702 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340472702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC 12/9/2017_PROD_SCORE210_ZONE1_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340489317/C2CE08E0AEB55B105E7BA7DEBB14BD4E220D3534/&quot;,
        ///		&quot;size&quot;: 4083
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340489317 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340489317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE Story Mode_PROD_SCORE143_ZONE1_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340511612/DD3141F6DE7BBDD77D162EC46FF4FBF4E192D205/&quot;,
        ///		&quot;size&quot;: 4677
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340511612 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340511612", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE SEEDED_PROD_SCORE55_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340512126/0E222A0D8AE7C7E32B4CDD069569AD3881D17B04/&quot;,
        ///		&quot;size&quot;: 1410
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340512126 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340512126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;12/9/2017_PROD_SCORE31_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340539302/07D607C5823871014339D6845F0AED5EFCADCBED/&quot;,
        ///		&quot;size&quot;: 1443
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340539302 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340539302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE Nocturna_PROD_SCORE488_ZONE2_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340574779/B6F63ACB7884E1FCBDEA70EE9E1442176B2CA82A/&quot;,
        ///		&quot;size&quot;: 5183
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340574779 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340574779", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC 12/9/2017_PROD_SCORE83_ZONE1_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340582264/1B0144284FFC0EB9259A95693A7C7DEFCDADC754/&quot;,
        ///		&quot;size&quot;: 3668
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340582264 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340582264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE Story Mode_PROD_SCORE27_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340618972/7A8A5CD2B080AE55DD9674D06D899DD208D44B8D/&quot;,
        ///		&quot;size&quot;: 359
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340618972 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340618972", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE SEEDED_PROD_SCORE0_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340654449/C9A3BC13687F220FBADEA74F2BBA340122F96DDB/&quot;,
        ///		&quot;size&quot;: 319
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340654449 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340654449", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;12/9/2017_PROD_SCORE20_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340658917/FCC3498974B716F64FEAB6A0B19A8AB70C2E90D3/&quot;,
        ///		&quot;size&quot;: 463
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340658917 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340658917", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE Bard_PROD_SCORE102_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340661010/19DAD40338806239E5BD1E7CAC0302008F0EAB55/&quot;,
        ///		&quot;size&quot;: 5580
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340661010 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340661010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE_PROD_SCORE191_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340712746/9AA2D3D25C5BB95F35B1F03C87A5DD93567E951F/&quot;,
        ///		&quot;size&quot;: 2928
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340712746 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340712746", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;12/9/2017_PROD_SCORE173_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340796353/46899C8640A4C035D135234942694F5FE3401AE8/&quot;,
        ///		&quot;size&quot;: 3210
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340796353 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340796353", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;12/9/2017_PROD_SCORE25_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/844845073340843735/354E39D111D3DB76C29CD2502EFF73E79B905927/&quot;,
        ///		&quot;size&quot;: 466
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_844845073340843735 {
            get {
                return ResourceManager.GetString("UgcFileDetails_844845073340843735", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE Story Mode_PROD_SCORE23_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592369232/749C620891553E9624F40B4668B51F705CBD040D/&quot;,
        ///		&quot;size&quot;: 1021
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592369232 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592369232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Error&gt;&lt;Code&gt;BlobNotFound&lt;/Code&gt;&lt;Message&gt;The specified blob does not exist.
        ///RequestId:2379f386-001e-0039-437e-30ada6000000
        ///Time:2017-09-18T13:04:51.6561964Z&lt;/Message&gt;&lt;/Error&gt;.
        /// </summary>
        internal static string UgcFileDetails_845970274592369232_NotFound {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592369232_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE_PROD_SCORE534_ZONE1_LEVEL4&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592383940/2D407B589507B8C85F33DD71D4DFD56DE245E6A4/&quot;,
        ///		&quot;size&quot;: 7820
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592383940 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592383940", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE_PROD_SCORE312_ZONE1_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592402923/0FB453BEEA6F40A00AE5A0AF325D71F1713EB1C3/&quot;,
        ///		&quot;size&quot;: 2968
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592402923 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592402923", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC 5/9/2017_PROD_SCORE1195_ZONE3_LEVEL4&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592404139/9021181A84A13D9D312E4F181A69E5EFD2E77678/&quot;,
        ///		&quot;size&quot;: 18941
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592404139 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592404139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE MYSTERY_PROD_SCORE278_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592417527/283602BCF733A9F6D5C681CE7A5F2E0250442232/&quot;,
        ///		&quot;size&quot;: 2954
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592417527 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592417527", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE SEEDED HARD_PROD_SCORE2668_ZONE5_LEVEL6&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592539966/55CF57BC8FB7B11F5E37002899D300DDFF6821F6/&quot;,
        ///		&quot;size&quot;: 46554
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592539966 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592539966", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC SEEDED SPEEDRUN HARD_PROD_SCORE97659881_ZONE5_LEVEL6&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592540128/55CF57BC8FB7B11F5E37002899D300DDFF6821F6/&quot;,
        ///		&quot;size&quot;: 46554
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592540128 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592540128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE Melody MYSTERY_PROD_SCORE3398_ZONE5_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592641888/1FD3D2166B6BCDBAF57913F5B3D09B5FB7D5B98D/&quot;,
        ///		&quot;size&quot;: 40458
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592641888 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592641888", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE MYSTERY_PROD_SCORE487_ZONE1_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592656129/FE52A001581795F447D5B58DDCA9F6A262DCEDEE/&quot;,
        ///		&quot;size&quot;: 3943
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592656129 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592656129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE PHASING_PROD_SCORE209_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592667508/96A74C304BC563D353C20815C944EE47BD7FBBA9/&quot;,
        ///		&quot;size&quot;: 3019
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592667508 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592667508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE_PROD_SCORE643_ZONE4_LEVEL6&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592678894/C3DE3E9BA93C89001A62F4659C77AAD96E0F413E/&quot;,
        ///		&quot;size&quot;: 35578
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592678894 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592678894", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;SPEEDRUN_PROD_SCORE98067457_ZONE4_LEVEL6&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592679004/C3DE3E9BA93C89001A62F4659C77AAD96E0F413E/&quot;,
        ///		&quot;size&quot;: 35578
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592679004 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592679004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE Bard PHASING_PROD_SCORE4484_ZONE5_LEVEL6&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592783564/9D6F6B679C594FEC34EB76FC90F00F325692D1D2/&quot;,
        ///		&quot;size&quot;: 30341
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592783564 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592783564", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC SPEEDRUN Bard PHASING_PROD_SCORE98017110_ZONE5_LEVEL6&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592783747/9D6F6B679C594FEC34EB76FC90F00F325692D1D2/&quot;,
        ///		&quot;size&quot;: 30341
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592783747 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592783747", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC SPEEDRUN_PROD_SCORE97674899_ZONE5_LEVEL6&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970274592823214/96A269315EC580FC9959811DB5BBC255EBE607CD/&quot;,
        ///		&quot;size&quot;: 43453
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970274592823214 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970274592823214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC 5/9/2017_PROD_SCORE174_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216224430/CD863E56B3B2B4885D4D5EDDFCA128B879B504CE/&quot;,
        ///		&quot;size&quot;: 1753
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216224430 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216224430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE Diamond RANDOMIZER_PROD_SCORE246_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216237024/32D5AF9D0C6AE4964B0AC1DE4854E58CE34A62AC/&quot;,
        ///		&quot;size&quot;: 1333
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216237024 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216237024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE Aria_PROD_SCORE265_ZONE4_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216294057/64E00BB59C2673D3BCF034E8F692E7E6454AD47C/&quot;,
        ///		&quot;size&quot;: 3709
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216294057 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216294057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC 6/9/2017_PROD_SCORE4410_ZONE3_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216353794/17A1CA69364D4D93834C0D97CE304BBDFD9ABAE2/&quot;,
        ///		&quot;size&quot;: 12860
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216353794 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216353794", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;SPEEDRUN Bard_PROD_SCORE98525016_ZONE4_LEVEL6&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216404327/F7CE30C31124F528AA51D2AFC67D443B5F88D027/&quot;,
        ///		&quot;size&quot;: 39641
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216404327 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216404327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;6/9/2017_PROD_SCORE2916_ZONE4_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216460106/0A9A35A3C1D2C716C16CBE1F9D8A6898BCFC2DF3/&quot;,
        ///		&quot;size&quot;: 19864
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216460106 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216460106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;6/9/2017_PROD_SCORE705_ZONE2_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216468628/2C61F2CEA900AD40E52743936314C88EEC9112B0/&quot;,
        ///		&quot;size&quot;: 6185
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216468628 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216468628", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC 6/9/2017_PROD_SCORE3892_ZONE5_LEVEL6&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216482197/5728DE896EB5EB2813613ACDB4A194A9BD3B8347/&quot;,
        ///		&quot;size&quot;: 50679
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216482197 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216482197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;6/9/2017_PROD_SCORE210_ZONE1_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216614550/41771F71E93AF82553ECED3EE2ABA8ADE3373200/&quot;,
        ///		&quot;size&quot;: 3579
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216614550 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216614550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC 6/9/2017_PROD_SCORE7759_ZONE5_LEVEL5&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216627104/95C3D45FDACD49A26378F17548C67CCDB63A73FC/&quot;,
        ///		&quot;size&quot;: 47785
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216627104 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216627104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;6/9/2017_PROD_SCORE112_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216647618/19E802BCBE752F915FA36E892E3578B59CB6C831/&quot;,
        ///		&quot;size&quot;: 2888
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216647618 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216647618", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE Monk_PROD_SCORE6_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216663674/D5A79B3E560C1138C8B19E27D5FA212276E50C5B/&quot;,
        ///		&quot;size&quot;: 730
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216663674 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216663674", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE Monk DEATHLESS_PROD_SCORE0_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216677651/86C4D185D688BAA380BC62DAC551F4A4663F9D3A/&quot;,
        ///		&quot;size&quot;: 145
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216677651 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216677651", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;6/9/2017_PROD_SCORE186_ZONE1_LEVEL4&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216722085/E366B1AD454EC0D099AFE72AC9E5F946192D248A/&quot;,
        ///		&quot;size&quot;: 6166
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216722085 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216722085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE Story Mode_PROD_SCORE165_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216735376/A338C7F7722A0DA5B61722F88096E8013AEC24CC/&quot;,
        ///		&quot;size&quot;: 3490
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216735376 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216735376", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;HARDCORE_PROD_SCORE272_ZONE2_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216743053/EF389C60524DAAC2A86AB4CA2403956857C7E23A/&quot;,
        ///		&quot;size&quot;: 7566
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216743053 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216743053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;6/9/2017_PROD_SCORE59_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216748528/E7EFFA44B0B874D2F0C475B1B5B3BC88864D761B/&quot;,
        ///		&quot;size&quot;: 948
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216748528 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216748528", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE RANDOMIZER_PROD_SCORE4034_ZONE4_LEVEL4&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216837544/6A87752F3CD0953982B3EC452E3DC426508600BE/&quot;,
        ///		&quot;size&quot;: 27135
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216837544 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216837544", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE Aria_PROD_SCORE375_ZONE1_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216845676/7669BCAB8BE7A3AF4CACE876B6EAC82C3F6FCF83/&quot;,
        ///		&quot;size&quot;: 4001
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216845676 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216845676", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE RANDOMIZER_PROD_SCORE171_ZONE1_LEVEL2&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216964529/45E9DA6C71D26FC0FBB7CBCB1D2F123732188811/&quot;,
        ///		&quot;size&quot;: 2730
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216964529 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216964529", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE_PROD_SCORE396_ZONE2_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351216998233/6AEC56ABC474BA319FF1FB19616237A44CBFEF69/&quot;,
        ///		&quot;size&quot;: 11564
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351216998233 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351216998233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE RANDOMIZER_PROD_SCORE2119_ZONE3_LEVEL4&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351217037549/4E36367CB159295776BD2B6801FA44CF5C380DA1/&quot;,
        ///		&quot;size&quot;: 21908
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351217037549 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351217037549", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE MYSTERY_PROD_SCORE87_ZONE1_LEVEL1&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351217043243/F8D5AE3C3662E6AE26B1565758702D3E54BB09CF/&quot;,
        ///		&quot;size&quot;: 1167
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351217043243 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351217043243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE MYSTERY_PROD_SCORE188_ZONE1_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351217061481/80123E31A2C784D5171D383ED832F44EF5D545F6/&quot;,
        ///		&quot;size&quot;: 5319
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351217061481 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351217061481", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC 6/9/2017_PROD_SCORE1305_ZONE2_LEVEL4&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351217127622/8A20EE5D92DAD7E06BE8C6BC2E6591B8CB38D884/&quot;,
        ///		&quot;size&quot;: 13583
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351217127622 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351217127622", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE Tempo HARD_PROD_SCORE1320_ZONE1_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351217136579/680F0AF9EBD5D915A2CEC5BAB186FA7EDB4FE6DF/&quot;,
        ///		&quot;size&quot;: 4051
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351217136579 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351217136579", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC SPEEDRUN_PROD_SCORE97460146_ZONE5_LEVEL6&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351217310845/AB3A5D78136231A85ADABE91DDE687D38F79E84B/&quot;,
        ///		&quot;size&quot;: 50820
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351217310845 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351217310845", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC 6/9/2017_PROD_SCORE5982_ZONE3_LEVEL4&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351217341480/1D2EADAFE681E8E801E8CAB0B1AAEE101A3FADB0/&quot;,
        ///		&quot;size&quot;: 18689
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351217341480 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351217341480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data&quot;: {
        ///		&quot;filename&quot;: &quot;DLC HARDCORE Melody_PROD_SCORE317_ZONE1_LEVEL3&quot;,
        ///		&quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/845970351217499797/C037E8872756B56162B20639E94FF3C21A5D06CA/&quot;,
        ///		&quot;size&quot;: 3926
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_845970351217499797 {
            get {
                return ResourceManager.GetString("UgcFileDetails_845970351217499797", resourceCulture);
            }
        }
    }
}
