//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.Services.ReplaysService.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.Services.ReplaysService.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RawReplayData {
            get {
                object obj = ResourceManager.GetObject("RawReplayData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;total&quot;:54537,&quot;replays&quot;:[{&quot;id&quot;:&quot;844845073340377377&quot;,&quot;error&quot;:null,&quot;seed&quot;:null,&quot;version&quot;:null,&quot;killed_by&quot;:null},{&quot;id&quot;:&quot;844845073340436306&quot;,&quot;error&quot;:null,&quot;seed&quot;:null,&quot;version&quot;:null,&quot;killed_by&quot;:null},{&quot;id&quot;:&quot;844845073340472702&quot;,&quot;error&quot;:null,&quot;seed&quot;:null,&quot;version&quot;:null,&quot;killed_by&quot;:null},{&quot;id&quot;:&quot;844845073340489317&quot;,&quot;error&quot;:null,&quot;seed&quot;:null,&quot;version&quot;:null,&quot;killed_by&quot;:null},{&quot;id&quot;:&quot;844845073340511612&quot;,&quot;error&quot;:null,&quot;seed&quot;:null,&quot;version&quot;:null,&quot;killed_by&quot;:null},{&quot;id&quot;:&quot;844845073340512126&quot;,&quot;error&quot;:null,&quot;seed&quot;:null,&quot;version&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StaleReplays {
            get {
                return ResourceManager.GetString("StaleReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;status&quot;: {
        ///		&quot;code&quot;: 9
        ///	}
        ///}.
        /// </summary>
        internal static string UgcFileDetails_847096111522125255_NotFound {
            get {
                return ResourceManager.GetString("UgcFileDetails_847096111522125255_NotFound", resourceCulture);
            }
        }
    }
}
